#配置数据源
mybatis:
  type-aliases-package: new_qingzhu.demo.Pojo
  mapper-locations: classpath:Mapper/*.xml
#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

spring:
  #开发时关闭页面缓存，以求看到实时页面
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false
  datasource:
    #使用阿里的druid作为连接池，更多配置可参照druid starter的中文文档
    # 使用 druid 作为连接池  更多配置的说明可以参见 druid starter 中文文档 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/qingzhu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: 5973666
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始化时建立的连接个数，初始化会发生在显式调用init方法时，或者第一次getConnection时
      initialSize: 5
      #最小连接池数量
      minIdle: 5
      #最大连接池数量
      maxActive: 50
      #获取连接时的最大等待时间，单位是毫秒，配置maxWait之后，缺省启用公平锁
      maxWait: 60000
      #Destroy线程会检测连接的时间间隔，如果连接空闲大于等于minEvictableIdleTimeMillis则关闭物理连接
      timeBetweenEvictionRunsMillis: 60000
      #连接保持空闲而不被驱逐的最小时间
      minEvictableIdleTimeMillis: 300000
      #是否缓存preparedStatement,也就是PSCache,mysql 5.5以上有建议开启
      poolPreparedStatements: true
      #要启用PSCache，必须配置大于0,当大于0时，poolPreparedStatements自动触发修改为ture
      maxOpenPreparedStatements: 50
      #用来检查连接是否有有效的sql语句，根据数据库不同而不同
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

      validationQuery: SELECT 1
      #建议配置为ture ,不影响性能，并且保证了安全性，申请连接时检测，如果剩余时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，开启性能会降低
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，开启性能会降低
      testOnReturn: false
      #是否自动收回超时连接
      removeAbandoned: true
      #超时时间：秒
      removeAbandonedTimeOut: 180
      # druid 监控的配置 如果不使用 druid 的监控功能的话 以下配置就不是必须的
      # 本项目监控台访问地址: http://localhost:8080/druid/login.html

      # WebStatFilter用于采集web-jdbc关联监控的数据。
      # 更多配置可参见: https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_%E9%85%8D%E7%BD%AEWebStatFilter
      web-stat-filter:
        # 是否开启 WebStatFilter 默认是true
        enabled: true
        # 需要拦截的url
        url-pattern: /*
        # 排除静态资源的请求
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      # Druid内置提供了一个StatViewServlet用于展示Druid的统计信息。
      # 更多配置可参见:https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
      stat-view-servlet:
        #是否启用StatViewServlet 默认值true
        enabled: true
        # 需要拦截的url
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: admin
        login-password: wyf993??

